apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_ALTERNATIVE_DEPLOYMENT_1_NAME}-deployment
  namespace: ${K8S_APP_NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: ${PROJECT_NAME}-${K8S_ALTERNATIVE_DEPLOYMENT_1_NAME}-app
        envFrom:
        - configMapRef:
            name: ${PROJECT_NAME}-${K8S_ALTERNATIVE_DEPLOYMENT_1_NAME}-app-env-variables-file