apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: ${K8S_APP_NAMESPACE}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: ${K8S_CONTAINER_PORT}
  type: ClusterIP
