apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx-app
      initContainers:
      - name: ${PROJECT_NAME}-init-container
        image: ${K8S_DOCKER_IMAGE}:${K8S_DOCKER_TAG}
        command: ${K8S_INIT_CONTAINER_COMMAND}
        volumeMounts:
          - name: ${PROJECT_NAME}-app-volume
            mountPath: ${K8S_VOLUME_MOUNT_PATH}
        resources:
          limits:
            cpu: "${K8S_CONTAINER_CPU_LIMIT}"
            memory: "${K8S_CONTAINER_RAM_LIMIT}"
          requests:
            cpu: "${K8S_CONTAINER_CPU_REQUEST}"
            memory: "${K8S_CONTAINER_RAM_REQUEST}"