apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      volumes:
        - name: mongodb-key-volume
          configMap:
            name: mongodb-key
      containers:
      - name: ${PROJECT_NAME}-app
        volumeMounts:
          - name: mongodb-key-volume
            mountPath: ${K8S_CONTAINER_WORKINGDIR_PATH}/certificates/mongodb-key.pem
            subPath: mongodb-key.pem
