apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml

commonLabels:
  app: ${PROJECT_NAME}-nginx
  project: ${PROJECT_NAME}
  environment: ${K8S_ENV}

namePrefix: ${PROJECT_NAME}-nginx-
namespace: ${K8S_APP_NAMESPACE}