apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml

commonLabels:
  app: ${PROJECT_NAME}
  project: ${PROJECT_NAME}
  environment: ${K8S_ENV}

namePrefix: ${PROJECT_NAME}-
namespace: ${K8S_APP_NAMESPACE}