apiVersion: v1
kind: Service
metadata:
  name: service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "${PROJECT_DOMAIN_NAME}"
    service.beta.kubernetes.io/do-loadbalancer-name: "${PROJECT_DOMAIN_NAME}"
spec:
  type: LoadBalancer
