apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: http-nginx
    port: ${K8S_NODE_PORT}
    protocol: TCP
    nodePort: ${K8S_NGINX_NODE_PORT}
    targetPort: 80
  type: NodePort