apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: ${K8S_NODE_PORT}
    targetPort: ${K8S_CONTAINER_PORT}
  type: NodePort
