apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: ${PROJECT_NAME}-app
        envFrom:
        - configMapRef:
            name: ${PROJECT_NAME}-app-env-variables-file