#FROM node:10-alpine AS builder
#FROM node:8-alpine AS builder
FROM node:12-alpine AS builder
WORKDIR /usr/app
COPY package.json ./
RUN yarn
COPY . /usr/app
RUN yarn build

FROM nginx:alpine
COPY --from=builder /usr/app/build /usr/share/nginx/html
EXPOSE 80
#COPY ./nginx.conf /etc/nginx/conf.d/default.conf   # rewrite default nginx.conf
CMD ["nginx", "-g", "daemon off;"]