# => Run container
FROM nginx:1.15.2-alpine

# Nginx config
#RUN rm -rf /etc/nginx/conf.d && \
#    ls -la
WORKDIR /var/www

RUN rm -fv /etc/nginx/nginx.conf
COPY docker/conf/nginx.conf /etc/nginx/nginx.conf

# Static build
#COPY --from=builder /app/build /usr/share/nginx/html/
COPY ./build /var/www

# Default port exposure
EXPOSE 80

# Copy .env file and shell script to container

CMD ["nginx", "-g", "daemon off;"]
